version: '3.8'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/akatsuya/workspace/gaimu:/workspace
      - /home/akatsuya/.bash_history:/home/vscode/.bash_history
    command: sleep infinity