version: '3.8'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/${USER}/workspace/gaimu:/workspace
      - /home/${USER}/.bash_history:/home/vscode/.bash_history
    command: sleep infinity